swagger: "2.0"

info:
  version: 1.0.0
  title: Agent Configuration MS API
schemes:
  - http
basePath: /staff
produces:
  - application/json

paths:
  /health:
    get:
      description: application health check
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Health'
            type: array
      summary: application health check

  /signup:
    post:
      consumes:
        - application/json
      description: User registration
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          schema:
            $ref: '#/definitions/models.UserRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Error'
      summary: User registration

  /signin:
    post:
      consumes:
        - application/json
      description: User sign in
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          schema:
            $ref: '#/definitions/models.Credentials'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Error'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Error'
      summary: User sign in

  /password/required:
    post:
      consumes:
        - application/json
      description: Changing temporary password
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          schema:
            $ref: '#/definitions/models.Credentials'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Error'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Error'
      summary: Changing temporary password

  /signout:
    post:
      tags:
        - Authorised
      consumes:
        - application/json
      description: Removes tokens from cookies
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Error'
      summary: Removes tokens from cookies

  /user:
    get:
      tags:
        - Authorised
      consumes:
        - application/json
      description: Retrieves authorised user data
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/common.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Error'
      summary: Retrieves user data
    put:
      tags:
        - Authorised
      consumes:
        - application/json
      description: Updates basic user data
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          schema:
            $ref: '#/definitions/models.UserUpdate'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/common.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Error'
      summary: Updates basic user data

  /user/{id}:
    get:
      tags:
        - Authorised
      consumes:
        - application/json
      description: Retrieves user data
      parameters:
        - $ref: '#/parameters/ObjectID'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/common.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Error'
      summary: Retrieves user data
    put:
      tags:
        - Admin Only
      consumes:
        - application/json
      description: Updates full user data
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/ObjectID'
        - in: body
          name: user
          schema:
            $ref: '#/definitions/models.AdminUserUpdate'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/common.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Error'
      summary: Updates full user data

  /user/search:
    post:
      tags:
        - Authorised
      consumes:
        - application/json
      description: Search user by name
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          schema:
            $ref: '#/definitions/models.UserSearch'
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/models.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Error'
      summary: Search user by name


  /user/photo:
    post:
      tags:
        - Authorised
      consumes:
        - "multipart/form-data"
      description: Upload user photo
      produces:
        - application/json
      parameters:
        - in: formData
          name: photo
          type: file
          required: true
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/models.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Error'
      summary: Upload user photo


definitions:

  common.Error:
    properties:
      message:
        type: string
    type: object

  models.UserRequest:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      position:
        type: string
      email:
        type: string
      role:
        type: string
        enum: ["admin", "user"]

  models.UserResponse:
    type: object
    properties:
      id:
        type: string
        format: uuid
      firstName:
        type: string
      lastName:
        type: string
      position:
        type: string
      email:
        type: string
      role:
        type: string
        enum: [admin, user]
      mobilePhone:
        type: string
      dateOfBirth:
        type: string
      imageURL:
        type: string

  models.Credentials:
    type: object
    properties:
      password:
        type: string
      email:
        type: string

  models.UserUpdate:
    type: object
    properties:
      mobilePhone:
        type: string
      dateOfBirth:
        type: string

  models.AdminUserUpdate:
    type: object
    properties:
      mobilePhone:
        type: string
      dateOfBirth:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      position:
        type: string
      role:
        type: string
        enum: ["admin", "user"]

  models.UserSearch:
    type: object
    properties:
      name:
        type: string
        description: "Search can work with several symbols"
      position:
        type: string
        description: "Should be provided full word (optional)"



  models.Health:
    properties:
      currentTime:
        type: string
      startTime:
        type: string
      networkInterfaces:
        type: array
        items:
          type: string
      connections:
        type: array
        items:
          type: object
          properties:
            serviceName:
              type: string
            activeNodes:
              type: array
              items:
                type: string
            downNodes:
              type: array
              items:
                type: string


parameters:
  ObjectID:
    in: path
    name: id
    type: string
    format: uuid
    required: true

